"""added new column and removed another to user_metrics

Revision ID: 46a5543419fd
Revises: e4d3f6c1b2a9
Create Date: 2026-04-04 08:41:07.084043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46a5543419fd'
down_revision: Union[str, Sequence[str], None] = 'e4d3f6c1b2a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_metrics', sa.Column('adherence', sa.Float(), nullable=True))
    op.drop_column('user_metrics', 'unhealthy_ratio')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_metrics', sa.Column('unhealthy_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('user_metrics', 'adherence')
    # ### end Alembic commands ###
